---
spring:
  kafka:
    bootstrap-servers: ${STREAMING_KAFKA_BROKER_URL:localhost:29092}

springfox:
  documentation:
    auto-startup: false

logger:
  namespace: company-links-consumer

api:
  endpoint: ${API_URL:localhost}
  company-profile-api-key: ${COMPANY_PROFILE_API_KEY:localhost}

company-links:
  consumer:
    insolvency:
      enable: true
      group-id: company-links-consumer
      topic: stream-insolvency
      attempts: 4
      backoff-delay: 100

    charges:
      enable: true
      group-id: company-links-consumer
      topic: stream-charges

