spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: company-links-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

insolvency:
  stream:
    topic:
      main: stream-insolvency-topic
      retry: stream-insolvency-topic-retry
      error: stream-insolvency-topic-error

charges:
  stream:
    topic:
      main: stream-charges-topic
      retry: stream-charges-topic-retry
      error: stream-charges-topic-error

logger:
  namespace: company-links-consumer

api:
    endpoint: ${COMPANY_PROFILE_API_URL:localhost}
