server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: ${STREAMING_KAFKA_BROKER_URL:localhost:29092}
    listener:
      concurrency: ${COMPANY_LINKS_LISTENER_CONCURRENCY:1}

springfox:
  documentation:
    auto-startup: false

logger:
  namespace: company-links-consumer

api:
  api-url: ${ERIC_API_URL:http://localhost:8888}
  api-key: ${ERIC_API_KEY:localhost}

company-links:
  consumer:
    insolvency:
      enable: ${COMPANY_LINKS_CONSUMER_INSOLVENCY_ENABLED:true}
      group-id: ${COMPANY_LINKS_CONSUMER_INSOLVENCY_GROUP_ID:company-links-consumer}
      topic: ${COMPANY_LINKS_CONSUMER_INSOLVENCY_TOPIC:stream-company-insolvency}
      attempts: ${COMPANY_LINKS_CONSUMER_INSOLVENCY_ATTEMPTS:4}
      backoff-delay: ${COMPANY_LINKS_CONSUMER_INSOLVENCY_BACKOFF_DELAY:100}

    charges:
      enable: ${COMPANY_LINKS_CONSUMER_CHARGES_ENABLED:true}
      group-id: ${COMPANY_LINKS_CONSUMER_CHARGES_GROUP_ID:company-links-consumer}
      topic: ${COMPANY_LINKS_CONSUMER_CHARGES_TOPIC:stream-company-charges}
      attempts: ${COMPANY_LINKS_CONSUMER_CHARGES_ATTEMPTS:4}
      backoff-delay: ${COMPANY_LINKS_CONSUMER_CHARGES_BACKOFF_DELAY:100}

    exemptions:
      enable: ${COMPANY_LINKS_CONSUMER_EXEMPTIONS_ENABLED:true}
      group-id: ${COMPANY_LINKS_CONSUMER_EXEMPTIONS_GROUP_ID:company-links-consumer}
      topic: ${COMPANY_LINKS_CONSUMER_EXEMPTIONS_TOPIC:stream-company-exemptions}
      attempts: ${COMPANY_LINKS_CONSUMER_EXEMPTIONS_ATTEMPTS:4}
      backoff-delay: ${COMPANY_LINKS_CONSUMER_EXEMPTIONS_BACKOFF_DELAY:100}

    officers:
      enable: ${COMPANY_LINKS_CONSUMER_OFFICERS_ENABLED:true}
      group-id: ${COMPANY_LINKS_CONSUMER_OFFICERS_GROUP_ID:company-links-consumer}
      topic: ${COMPANY_LINKS_CONSUMER_OFFICERS_TOPIC:stream-company-officers}
      attempts: ${COMPANY_LINKS_CONSUMER_OFFICERS_ATTEMPTS:4}
      backoff-delay: ${COMPANY_LINKS_CONSUMER_OFFICERS_BACKOFF_DELAY:100}

    statements:
      enable: ${COMPANY_LINKS_CONSUMER_STATEMENTS_ENABLED:true}
      group-id: ${COMPANY_LINKS_CONSUMER_STATEMENTS_GROUP_ID:company-links-consumer}
      topic: ${COMPANY_LINKS_CONSUMER_STATEMENTS_TOPIC:stream-company-officers}
      attempts: ${COMPANY_LINKS_CONSUMER_STATEMENTS_ATTEMPTS:4}
      backoff-delay: ${COMPANY_LINKS_CONSUMER_STATEMENTS_BACKOFF_DELAY:100}

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /company-links-consumer
      path-mapping:
        health: healthcheck
  endpoint:
    health:
      show-details: never
      enabled: true