---
spring:
  kafka:
    bootstrap-servers: ${STREAMING_KAFKA_BROKER_URL:localhost:29092}

springfox:
  documentation:
    auto-startup: false

logger:
  namespace: company-links-consumer

api:
  endpoint: ${COMPANY_PROFILE_API_URL:http://localhost:8888}
  company-profile-api-key: ${COMPANY_PROFILE_API_KEY:localhost}

company-links:
  consumer:
    insolvency:
      enable: ${COMPANY_LINKS_CONSUMER_INSOLVENCY_ENABLED:true}
      group-id: ${COMPANY_LINKS_CONSUMER_INSOLVENCY_GROUP_ID:company-links-consumer}
      topic: ${COMPANY_LINKS_CONSUMER_INSOLVENCY_TOPIC:stream-company-insolvency}
      attempts: ${COMPANY_LINKS_CONSUMER_INSOLVENCY_ATTEMPTS:4}
      backoff-delay: ${COMPANY_LINKS_CONSUMER_INSOLVENCY_BACKOFF_DELAY:100}

    charges:
      enable: ${COMPANY_LINKS_CONSUMER_CHARGES_ENABLED:true}
      group-id: ${COMPANY_LINKS_CONSUMER_CHARGES_GROUP_ID:company-links-consumer}
      topic: ${COMPANY_LINKS_CONSUMER_CHARGES_TOPIC:stream-company-charges}
      attempts: ${COMPANY_LINKS_CONSUMER_CHARGES_ATTEMPTS:4}
      backoff-delay: ${COMPANY_LINKS_CONSUMER_CHARGES_BACKOFF_DELAY:100}

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /company-links-consumer
      path-mapping:
        health: healthcheck
  endpoint:
    health:
      show-details: never
      enabled: true