---
spring:
  kafka:
    bootstrap-servers: ${DATA_SYNC_KAFKA_BROKER_URL:localhost:29092}

springfox:
  documentation:
    auto-startup: false

logger:
  namespace: company-links-consumer

api:
  endpoint: ${API_URL:http://localhost:8888}
  company-profile-api-key: ${COMPANY_PROFILE_API_KEY:MGQ1MGNlYmFkYzkxZTM2MzlkNGVmMzg4ZjgxMmEz}

company-links:
  consumer:
    insolvency:
      enable: true
      group-id: company-links-consumer
      topic:
        main: stream-insolvency

    charges:
      enable: false
      group-id: company-links-consumer
      topic:
        main: stream-charges

