spring:
  kafka:
    bootstrap-servers: ${DATA_SYNC_KAFKA_BROKER_URL:localhost:9092}

springfox:
  documentation:
    auto-startup: false

insolvency:
  stream:
    group-id: company-links-consumer
    topic:
      main: stream-insolvency-topic
      retry: stream-insolvency-topic-retry

charges:
  stream:
    group-id: company-links-consumer
    topic:
      main: stream-charges-topic
      retry: stream-charges-topic-retry

logger:
  namespace: company-links-consumer

api:
  endpoint: ${COMPANY_PROFILE_API_URL:localhost}
  company-profile-api-key: ${COMPANY_PROFILE_API_KEY:localhost}

company-links:
  consumer:
    insolvency:
      enable: true
    charges:
      enable: false

