server:
  port: 8084

spring:
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 1

logger:
  namespace: company-links-consumer

api:
  api-url: http://localhost:8888
  api-key: MGQ1MGNlYmFkYzkxZTM2MzlkNGVmMzg4ZjgxMmEz

company-links:
  consumer:
    insolvency:
      enable: true
      group-id: company-links-consumer
      topic: stream-company-insolvency
      attempts: 4
      backoff-delay: 10

    charges:
      enable: true
      group-id: company-links-consumer
      topic: stream-company-charges
      attempts: 4
      backoff-delay: 10

    exemptions:
      enable: true
      group-id: company-links-consumer
      topic: stream-company-exemptions
      attempts: 4
      backoff-delay: 10

wiremock:
  server:
  port: 8888