spring:
  kafka:
    bootstrap-servers: localhost:9092

insolvency:
  stream:
    topic:
      main: {$STREAM_INSOLVENCY_TOPIC:stream-insolvency-topic} #TODO how to define the EV
      retry: {$STREAM_INSOLVENCY_TOPIC_RETRY:stream-insolvency-topic-retry}
      error: {$STREAM_INSOLVENCY_TOPIC_ERROR:stream-insolvency-topic-error}

charges:
  stream:
    topic:
      main: {$STREAM_CHARGES_TOPIC:stream-charges-topic}
      retry: {$STREAM_CHARGES_TOPIC_RETRY:stream-charges-topic-retry}
      error: {$STREAM_CHARGES_TOPIC_ERROR:stream-charges-topic-error}

company-links:
  consumer:
    insolvency:
      enable: true
      group-id: company-links-consumer
      topic: stream-company-insolvency
    charges:
      enable: true
      group-id: company-links-consumer
      topic: stream-company-charges

logger:
  namespace: company-links-consumer

api:
  endpoint: ${COMPANY_PROFILE_API_URL:http://localhost:8888}
  company-profile-api-key: ${COMPANY_PROFILE_API_KEY:MGQ1MGNlYmFkYzkxZTM2MzlkNGVmMzg4ZjgxMmEz}
  charges-data-api-url: ${CHARGES_DATA_API_URL:localhost}
  charges-data-api-key: ${CHARGES_DATA_API_KEY:localhost}

wiremock:
  server:
    port: 8888